var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/about/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__da290621._.js")
R.c("server/chunks/ssr/src_app_about_page_tsx_2ebe742f._.js")
R.c("server/chunks/ssr/_17ed2179._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ff0ebc97._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e82ee19._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__32595aaa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_about_page_actions_6fff35e4.js")
R.m(50227)
module.exports=R.m(50227).exports
